require_relative "plotters/abstract_plotter"
require_relative "plotters/random_support"
require_relative "plotters/estimation_support"
require_relative "plotters/categorical_plotter"
require_relative "plotters/bar_plotter"
require_relative "plotters/box_plotter"
