require_relative "plotters/abstract_plotter"
require_relative "plotters/random_support"
require_relative "plotters/estimation_support"
require_relative "plotters/categorical_plotter"
require_relative "plotters/bar_plotter"
require_relative "plotters/box_plotter"
require_relative "plotters/count_plotter"

require_relative "plotters/vector_plotter"
require_relative "plotters/relational_plotter"
require_relative "plotters/scatter_plotter"
require_relative "plotters/line_plotter"

require_relative "plotters/distribution_plotter"
require_relative "plotters/histogram_plotter"
