require_relative "charty/version"

require "colors"
require "palette"

require_relative "charty/util"
require_relative "charty/backends"
require_relative "charty/backend_methods"
require_relative "charty/plotter"
require_relative "charty/index"
require_relative "charty/layout"
require_relative "charty/linspace"
require_relative "charty/missing_value_support"
require_relative "charty/plotters"
require_relative "charty/plot_methods"
require_relative "charty/table"
require_relative "charty/table_adapters"
require_relative "charty/statistics"
require_relative "charty/vector_adapters"
require_relative "charty/vector"
