require_relative "charty/version"

require_relative "charty/backends"
require_relative "charty/colors"
require_relative "charty/color_methods"
require_relative "charty/plotter"
require_relative "charty/layout"
require_relative "charty/linspace"
require_relative "charty/table_adapters"
require_relative "charty/table"
