# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

ruby '2.5.0'

gem 'mimemagic'

install_if -> { RUBY_PLATFORM !~ /darwin|mswin|mingw/ } do
  gem 'rbczmq'
end

gem 'cztop'
gem 'iruby'
gem 'matplotlib'
gem 'charty', path: ".."
