# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

ruby '2.5.0'

gem 'mimemagic'
gem 'rbczmq'
gem 'cztop'
gem 'iruby'
gem 'matplotlib'
gem 'charty', path: ".."
