name: CI with NMatrix

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  test:
    name: ${{ matrix.os }}/${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        ruby:
        - 2.7
        - 2.6

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - uses: actions/cache@v4
      if: runner.os == 'Linux'
      with:
        path: ~/.cache/red-datasets
        key: ${{ runner.os }}-${{ hashFiles('lib/**') }}
        restore-keys: ${{ runner.os }}-

    - uses: actions/cache@v4
      if: |
        runner.os == 'macOS'
      with:
        path: |
          ~/Library/Caches/red-datasets
        key: ${{ runner.os }}-${{ hashFiles('lib/**') }}
        restore-keys: ${{ runner.os }}-

    - uses: actions/cache@v4
      if: |
        runner.os == 'Windows'
      with:
        path: |
          ~/AppData/red-datasets
        key: ${{ runner.os }}-${{ hashFiles('lib/**') }}
        restore-keys: ${{ runner.os }}-

    - run: sudo apt install build-essential libsqlite3-dev

    - run: npm install playwright@latest
    - run: ./node_modules/.bin/playwright install

    - run: bundle install --jobs 4 --retry 3 --without "numo python"

    - run: bundle exec rake VERBOSE=1
      env:
        TIMEOUT_SEC: 180

    - run: rake build

    - run: gem install --user pkg/*.gem
